# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'CarBooking' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for CarBooking

  pod 'Moya'
  pod 'Moya/Combine'

  target 'CarBookingTests' do
      inherit! :search_paths
      pod 'Moya'
      pod 'Moya/Combine'
  end
end
